###

# @name AuthSeller
POST {{BASE_URL}}/sellers/auth
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456"
}

###

# @name AskRestPasswordSeller
POST {{BASE_URL}}/sellers/ask-reset-password
Content-Type: application/json

{
  "email": "test@gmail.com"
}

